### ISSUE TITLE
the returned result turns out to be an array

### ISSUE THREAD

**Issue by yucopowo** [axetroy/vm.js#17]
```js
var Test = function(text) {
  if (text) {
    var o = JSON.parse(text);
    this.id = o.id;
    this.list = o.list;
  } else {
    this.id = '';
    this.list = [];
  }
};

var test = new Test('{"id":1,"list":[]}');

console.log(test);
```

result
`[prototype: {…}] prototype : {constructor: ƒ} length : 0 __proto__ : Array(0)`

current
`array`
Expect
`object`

The run result is an array , but expected result is the object
but expected result is the object
t

**Comment by axetroy** [comment]
fixed!
